apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express

        env:
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://10.0.5.54:27017/dev?ssl=false"
        ports:
        - name: mongo-express
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksapp
  labels:
    app: tasksapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksapp
  template:
    metadata:
      labels:
        app: tasksapp
    spec:
      containers:
        - name: tasksapp
          image: public.ecr.aws/v4o5r6v9/tasksapp-python:4
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
          - name: MONGO_URI
            value: "mongodb://10.0.5.54:27017/dev"
          - name: JSONIFY_PRETTYPRINT_REGULAR
            value: "True"
---
apiVersion: v1
kind: Service
metadata:
  name: tasksapp-service
spec:
  selector:
    app: tasksapp
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer